apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      env: dev
    includeSelectors: false
    includeTemplates: false

resources:
  - ../../base

patches:
  - target:
      kind: HorizontalPodAutoscaler
    path: resources/hpa.yaml